export const mockContracts = [
  {
    id: '1',
    title: 'IT Help Desk Support Services',
    agency: 'General Services Administration',
    agencyShort: 'GSA',
    value: '$180,000',
    valueMin: 120000,
    valueMax: 180000,
    deadline: '2026-05-22',
    daysLeft: 11,
    match: 97,
    naics: '541512',
    location: 'Atlanta, GA',
    setAside: 'Small Business',
    postedDate: '2026-05-01',
    solicitationNumber: 'GSA-2026-IT-0041',
    description: `The General Services Administration (GSA) is seeking qualified small businesses to provide comprehensive IT help desk support services for its Region 4 offices located in Atlanta, GA. The contractor shall provide Tier 1 and Tier 2 support for approximately 400 federal employees, covering hardware troubleshooting, software installation, network connectivity issues, and user account management. Services shall be provided Monday through Friday, 7:00 AM to 6:00 PM EST. The contractor must maintain a maximum 4-hour response time for critical issues and 24-hour resolution for non-critical tickets. All personnel must be US citizens and capable of obtaining a Public Trust clearance.`,
    aiBreakdown: {
      summary: 'GSA needs an IT help desk team to support 400 federal employees in Atlanta. This is a daytime Monday-Friday contract covering basic IT support — password resets, hardware issues, software problems.',
      whoCanApply: 'Small businesses only. You must be based in or able to staff the Atlanta, GA area. All staff need to be US citizens.',
      keyRequirements: ['US citizen staff only', '4-hour response for critical issues', '24-hour resolution guarantee', 'Public Trust clearance eligible staff', 'On-site presence required in Atlanta'],
      ourTake: 'High match. Your IT consulting profile lines up directly with this. The set-aside means you only compete against other small businesses. Deadline gives you 11 days to prepare.',
    },
  },
  {
    id: '2',
    title: 'Janitorial and Custodial Services — VA Medical Center',
    agency: 'Department of Veterans Affairs',
    agencyShort: 'VA',
    value: '$94,000',
    valueMin: 80000,
    valueMax: 94000,
    deadline: '2026-05-27',
    daysLeft: 16,
    match: 91,
    naics: '561720',
    location: 'Phoenix, AZ',
    setAside: 'Veteran-Owned Small Business',
    postedDate: '2026-05-03',
    solicitationNumber: 'VA258-2026-B-0092',
    description: `The Department of Veterans Affairs, Phoenix VA Health Care System, requires janitorial and custodial services for its main medical center campus (approximately 380,000 sq ft). Services include daily cleaning of patient rooms, hallways, restrooms, administrative areas, and operating theaters. The contractor must comply with all VA infection control policies and CDC guidelines for healthcare environments. Personnel must pass VA background checks and complete VA-required training prior to start. This is a Service-Disabled Veteran-Owned Small Business (SDVOSB) set-aside.`,
    aiBreakdown: {
      summary: 'The VA needs a cleaning crew for a large medical center in Phoenix — 380,000 sq ft including patient rooms and operating areas. This is a SDVOSB set-aside, meaning only service-disabled veteran-owned businesses can bid.',
      whoCanApply: 'Service-Disabled Veteran-Owned Small Businesses (SDVOSB) only. Must be verified in the VA\'s VetBiz registry.',
      keyRequirements: ['SDVOSB certification required', 'Healthcare cleaning experience preferred', 'Background checks for all staff', 'Must follow VA infection control protocols', 'Phoenix, AZ on-site work'],
      ourTake: 'Strong match if you are SDVOSB certified. Healthcare cleaning is higher value than commercial cleaning. Get your VetBiz registry verification done first if you haven\'t.',
    },
  },
  {
    id: '3',
    title: 'Cybersecurity Assessment and Penetration Testing',
    agency: 'Department of Homeland Security',
    agencyShort: 'DHS',
    value: '$320,000',
    valueMin: 250000,
    valueMax: 320000,
    deadline: '2026-06-04',
    daysLeft: 24,
    match: 85,
    naics: '541519',
    location: 'Remote / Washington, DC',
    setAside: 'HUBZone Small Business',
    postedDate: '2026-05-05',
    solicitationNumber: 'DHS-2026-CISA-0188',
    description: `The Cybersecurity and Infrastructure Security Agency (CISA) within DHS requires comprehensive cybersecurity assessment and penetration testing services for multiple federal information systems. The contractor shall conduct vulnerability assessments, penetration testing, red team exercises, and provide detailed remediation reports. All work involves access to sensitive federal systems and requires Top Secret clearance for lead personnel. This is a HUBZone set-aside contract.`,
    aiBreakdown: {
      summary: 'DHS / CISA needs a cybersecurity firm to hack their own systems (legally) to find vulnerabilities. High-value contract at $320K but requires HUBZone certification and Top Secret clearance for your lead people.',
      whoCanApply: 'HUBZone certified small businesses only. Lead technical staff need Top Secret clearance.',
      keyRequirements: ['HUBZone certification required', 'Top Secret clearance for leads', 'Proven pen testing experience', 'FedRAMP knowledge preferred', 'Ability to handle classified systems'],
      ourTake: 'High value but high barrier. If you are not HUBZone certified this one is out. If you are, and have cleared personnel, this is a strong opportunity with 24 days to prepare.',
    },
  },
  {
    id: '4',
    title: 'Professional Translation Services — Spanish and Portuguese',
    agency: 'Department of State',
    agencyShort: 'DoS',
    value: '$65,000',
    valueMin: 50000,
    valueMax: 65000,
    deadline: '2026-05-30',
    daysLeft: 19,
    match: 78,
    naics: '541930',
    location: 'Remote',
    setAside: 'Women-Owned Small Business',
    postedDate: '2026-05-06',
    solicitationNumber: 'DOS-2026-TRN-0034',
    description: `The Department of State requires professional translation services for official documents, reports, and communications from English to Spanish and Portuguese (Brazilian). Translations must be certified and completed within 48 hours of submission for standard documents and 4 hours for urgent requests. Remote work is permitted. This is a Women-Owned Small Business (WOSB) set-aside.`,
    aiBreakdown: {
      summary: 'State Department needs certified English-to-Spanish and English-to-Portuguese translators. Fully remote work. WOSB set-aside only.',
      whoCanApply: 'Women-Owned Small Businesses (WOSB) certified through SBA. Translators must be certified and native-level.',
      keyRequirements: ['WOSB certification required', 'Certified translators on staff', '48-hour standard turnaround', '4-hour urgent turnaround', 'Remote — no office required'],
      ourTake: 'Moderate match. Good entry contract for a WOSB translation business — fully remote and manageable scope.',
    },
  },
  {
    id: '5',
    title: 'Landscaping and Grounds Maintenance — Federal Building Complex',
    agency: 'General Services Administration',
    agencyShort: 'GSA',
    value: '$48,000',
    valueMin: 40000,
    valueMax: 48000,
    deadline: '2026-06-10',
    daysLeft: 30,
    match: 72,
    naics: '561730',
    location: 'Denver, CO',
    setAside: 'Small Business',
    postedDate: '2026-05-08',
    solicitationNumber: 'GSA-2026-LND-0077',
    description: `GSA requires weekly landscaping and grounds maintenance services for a federal office complex in Denver, CO, comprising 3 buildings and approximately 4 acres of grounds. Services include mowing, edging, fertilizing, irrigation system maintenance, snow removal (October through April), and seasonal plantings. Must have proper licensing for pesticide application in Colorado.`,
    aiBreakdown: {
      summary: 'GSA needs a landscaping crew in Denver to maintain 4 acres of federal grounds year-round including snow removal in winter. Open to any small business.',
      whoCanApply: 'Any small business. Must be licensed for pesticide application in Colorado.',
      keyRequirements: ['Colorado pesticide license', 'Snow removal capability', 'Weekly service schedule', 'Denver, CO on-site work', 'Equipment must be commercial-grade'],
      ourTake: 'Lower value but steady 12-month income and low competition. Good first contract for a landscaping or property services business in the Denver area.',
    },
  },
  {
    id: '6',
    title: 'Data Entry and Administrative Support',
    agency: 'Social Security Administration',
    agencyShort: 'SSA',
    value: '$120,000',
    valueMin: 100000,
    valueMax: 120000,
    deadline: '2026-06-01',
    daysLeft: 21,
    match: 88,
    naics: '561410',
    location: 'Baltimore, MD (Hybrid)',
    setAside: 'Small Business',
    postedDate: '2026-05-04',
    solicitationNumber: 'SSA-2026-ADM-0055',
    description: `The Social Security Administration requires data entry and administrative support services for its central processing office in Baltimore, MD. Work includes data entry from physical forms into federal systems, document scanning and indexing, mail processing, and general office support. Hybrid schedule — 3 days on-site, 2 days remote. Staff must pass SSA background investigation.`,
    aiBreakdown: {
      summary: 'SSA needs a team for data entry and office support in Baltimore — hybrid schedule, 3 days on-site. Standard admin work with no special certifications required beyond background check.',
      whoCanApply: 'Any small business. Staff must pass SSA background investigation (standard, not clearance-level).',
      keyRequirements: ['Baltimore, MD access required', 'Background investigation for all staff', 'Typing speed minimum 50 WPM', 'Hybrid schedule — 3 days on-site', 'Federal system data entry experience preferred'],
      ourTake: 'High match for a staffing or admin services business. Low barrier to entry, $120K value, and SSA is a stable long-term client.',
    },
  },
];

export const mockUser = {
  name: 'Alex Rivera',
  businessName: 'Rivera Tech Solutions LLC',
  naics: ['541512', '541519'],
  certifications: ['Veteran-Owned', 'Small Business'],
  location: 'Atlanta, GA',
  services: 'IT help desk support, computer setup, software troubleshooting, network support, and cybersecurity consulting for small businesses and government offices.',
  contractSizeMin: 50000,
  contractSizeMax: 500000,
};
